# Setup - Kör koden i denna cell. Du behöver installera pandas med pip (pip install pandas)

In [ ]:
# This makes it so that jupyter wont just output the last line, but everything that gets outputted.
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import pandas as pd
import numpy as np

## Beskrivning

Kickstarter är en tjänst där vem som helst kan försöka få finansiering av privatpersoner och företag för att förverkliga ett projekt. Datan består några tusen projekt som varit publicerade. Om du blir osäker på vad Kickstarter är, googla! :-)

Uppgiften går ut på att använda pythonbiblioteket "pandas" för att arbeta med datan. Denna laboration förutsätter att ni har läst på och deltagit på lektioner om pandas för att behärska lösningarna.

### Använd jupyternotebook i vscode (Alternativ 1), rekommenderas
Lös notebooken i vscode. Du behöver då installera pandas med hjälp av pip eller conda, tex. "pip install pandas". Följ denna youtube-video: https://www.youtube.com/watch?v=jNk-ZmeIz6c&ab_channel=VeryAcademy
**OBS** OM DU SKA INKLUDERA EN VIRTUAL ENVIRONMENT (VENV) SÅ MÅSTE DU DÖPA DEN TILL "VENV" ELLER BYTA NAMN PÅ VAD SOM STÅR I .gitignore-filen TILL SAMMA NAMN SOM DIN VIRTUAL ENVIRONMENT. Du ska alltså inte pusha ut din virtual environment till git! I många fall behöver du ingen virtual environment (venv) utan du kan köra pip install pandas direkt. Försök byta "interpreter" genom att skriva ctrl + shift + p --> select interpreter --> testa alla dina olika versioner av python

Om du inte kan köra dina celler så ska du se till att du valt en "kernel" längst uppe till höger.


### Använd google colab för din notebook (Alternativ 2), rekommenderas ej
Du kan göra uppgiften genom att använda google colab, Du kommer att behöva ladda upp main.ipynb följt av att lägga till testdatan "kickstarter.csv". Tänk bara på att du åtminstone 2-3 gånger under tidens gång sparar filen, gör en commit i git och pushar ut. Sedan fortsätter du. Detta är nackdelen med colab, att vi inte kan jobba med git lika smidigt.

### Hur du arbetar i notebooken

- För **VARJE** cell ska koden du skrivit displaya resultatet av dina operationer så att jag kan följa stegen du tar (genom att helt enkelt skriva "df" på slutet av varje cell). För vissa celler kan du dessutom se vilken output jag förväntar mig från celler där det står "Ta ej bort denna cell", om du tar bort cellen försvinner outputten. 
- **Det ska gå att köra koden från början till slut och få samma resultat igen**
- Du ska beskriva koden i varje cell så att jag ser att du förstår vad du gör. 
- Använd dokumentationen som stöd [https://pandas.pydata.org/docs/reference/frame.html](https://pandas.pydata.org/docs/reference/frame.html)

## Sektion 1

### 1 Ladda in datasettet kickstarter.csv till en dataframe, döp den till "df"

In [8]:
df = pd.read_csv("kickstarter.csv")

### 2 Printa ut de 5 första raderna

In [9]:
df.head(5)

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_result,usd_funding_goal,company_address
0,1054480724ID,Luminoodle COLOR & BASECAMP: Versatile & Porta...,Product Design,Design,USD,2016-04-22,25000.0,2016-03-22 16:39:57,408052.0,successful,5085,US,98849$ usd,408052.00,25000.00,"Mary Grove, 30815"
1,1317034686ID,Liberty's work was accepted into the Library o...,Shorts,Film & Video,USD,2017-02-23,1100.0,2017-02-03 07:26:57,1106.0,successful,10,US,52486$ usd,1106.00,1100.00,"Garcia Tunnel, 77525"
2,121816660ID,Dusk - Open World Survival Horror (Canceled),Video Games,Games,GBP,2015-12-19,50000.0,2015-11-18 01:53:10,1625.0,canceled,58,GB,53482$ usd,2422.88,74550.09,"Payne Isle, 42813"
3,49882738ID,Eatsleeptrainrepeat,Web,Technology,SEK,2014-12-24,180000.0,2014-11-24 21:47:27,0.0,failed,0,SE,64632$ usd,0.00,23054.76,"Laura Stream, 08932"
4,1503277376ID,FLARE Video Project,Shorts,Film & Video,USD,2011-03-12,5000.0,2011-02-10 20:32:26,5025.0,successful,9,US,99272$ usd,5025.00,5000.00,"Andrew Pike, 24782"

In [10]:
# Ta ej bort denna cell

### 3 Printa ut 20 slumpmässiga rader från datasettet

In [11]:
df.sample(20)

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_result,usd_funding_goal,company_address
753,488146883ID,The Ladies of Manure 2013 Calendar,Photography,Photography,USD,2012-12-16,5000.0,2012-11-16 15:41:54,5135.11,successful,72,US,83853$ usd,5135.11,5000.00,"Dennis Via, 12150"
1960,348071805ID,Inspirational Travel for Starving Musicians,Country & Folk,Music,USD,2015-08-17,1600.0,2015-07-31 23:03:14,25.00,failed,1,US,76733$ usd,25.00,1600.00,"Amber Dale, 67939"
419,1131679232ID,Death Stylish iPhone Case,Crafts,Crafts,MXN,2017-11-25,60000.0,2017-09-26 23:19:56,10.00,failed,1,MX,80006$ usd,0.54,3213.02,"Bush Port, 53310"
108,937888094ID,'the romantic' - print run of a poetry book to...,Poetry,Publishing,USD,2011-07-30,500.0,2011-06-30 19:33:10,1713.80,successful,75,US,93324$ usd,1713.80,500.00,"Toni Estates, 02870"
1559,86320936ID,"Funding for my Debut Album: ""Seattle Rain"" (Ca...",Indie Rock,Music,USD,2015-09-30,1000.0,2015-08-31 07:23:48,0.00,canceled,0,US,75474$ usd,0.00,1000.00,"Whitaker Neck, 87695"
795,662889422ID,Sober Island Brewing Company,Drinks,Food,CAD,2016-11-04,25000.0,2016-10-05 18:03:07,13258.00,failed,95,CA,57100$ usd,9869.72,18610.88,"Hernandez Estate, 74045"
1211,1763891586ID,Savannah's Radical Jewelry Makeover,Public Art,Art,USD,2015-01-24,1100.0,2015-01-14 19:53:37,543.00,failed,23,US,81395$ usd,543.00,1100.00,"Patricia Motorway, 04930"
598,720847615ID,New Earl Wear & Haywire CD!,Country & Folk,Music,USD,2014-01-06,10000.0,2013-12-07 03:38:25,600.00,failed,5,US,58136$ usd,600.00,10000.00,"Benjamin Point, 61739"
1292,858654989ID,Cognition #2 - Black Shuck,Comic Books,Comics,GBP,2017-04-05,1000.0,2017-03-11 22:36:23,2689.00,successful,213,GB,91640$ usd,3340.33,1242.22,"Sanders Freeway, 32937"
1972,880236486ID,Lost Legends,Tabletop Games,Games,USD,2012-12-01,10000.0,2012-10-17 10:51:39,30820.01,successful,457,US,75823$ usd,30820.01,10000.00,"Thomas Junctions, 38475"
572,13246281ID,SunglassSleeves: Eyewear Accessory for the Act...,Product Design,Design,USD,2015-12-12,3000.0,2015-10-31 22:32:29,130.00,failed,8,US,55919$ usd,130.00,3000.00,"Anthony Lodge, 31328"
115,1483767058ID,Soap Bubble Chair,Product Design,Design,USD,2012-05-19,4000.0,2012-04-04 14:03:02,5026.00,successful,46,US,88390$ usd,5026.00,4000.00,"Tina Road, 37512"
1854,575257439ID,Wawahte: An Indian Residential Schools Documen...,Documentary,Film & Video,CAD,2015-02-28,16000.0,2015-01-16 21:39:05,16156.00,successful,45,CA,83786$ usd,12960.05,12834.91,"Perez Mission, 76837"
1186,1187344827ID,Be a part of dust from 1000 yr's next album,Indie Rock,Music,USD,2011-12-19,500.0,2011-11-04 18:10:24,590.00,successful,15,US,81188$ usd,590.00,500.00,"Crystal Prairie, 94893"
386,1947456690ID,Mossless 4: Public/Private/Portrait,Photobooks,Photography,USD,2016-05-11,12600.0,2016-04-12 02:59:24,13758.00,successful,263,US,91342$ usd,13758.00,12600.00,"Smith Rapid, 82869"
240,1806896388ID,The Blazin' Wing Challenge Video Collab,Restaurants,Food,CAD,2014-09-02,350.0,2014-08-21 21:12:13,472.00,successful,24,CA,54528$ usd,433.90,321.75,"Galloway Landing, 71387"
278,196054706ID,"Mayim, Kinneret and I: a Documentary",Documentary,Film & Video,USD,2011-03-19,5100.0,2011-02-17 04:48:04,5638.00,successful,88,US,62293$ usd,5638.00,5100.00,"Deborah Fork, 10397"
867,623056309ID,Eva Abraham Band Live @ The Square & Compass 1...,Country & Folk,Music,GBP,2017-12-23,3200.0,2017-11-21 18:39:53,4000.00,successful,95,GB,72310$ usd,5406.94,4325.55,"Joel Port, 83331"
1106,2107874918ID,'Heirloom',Narrative Film,Film & Video,USD,2012-02-11,35000.0,2011-12-13 06:27:06,10.00,failed,1,US,88872$ usd,10.00,35000.00,"Thomas Motorway, 38898"
1247,847100356ID,theMINIclassy: A new HQ for high-end children'...,Childrenswear,Fashion,USD,2015-05-16,15000.0,2015-03-17 18:40:43,1250.00,failed,25,US,58002$ usd,1250.00,15000.00,"David Underpass, 15790"

In [12]:
# Ta ej bort denna cell

### 4 Visa en sammanställning av information från din dataframe

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  2000 non-null   object
 1   name                2000 non-null   object
 2   category            2000 non-null   object
 3   main_category       2000 non-null   object
 4   currency            2000 non-null   object
 5   deadline            2000 non-null   object
 6   goal                2000 non-null   float64
 7   launched            2000 non-null   object
 8   pledged             2000 non-null   float64
 9   state               2000 non-null   object
 10  backers             2000 non-null   int64
 11  country             2000 non-null   object
 12  usd pledged         2000 non-null   object
 13  usd_pledged_result  2000 non-null   float64
 14  usd_funding_goal    2000 non-null   float64
 15  company_address     2000 non-null   object
dtypes: float64(4), int64(1), object(11)
memory usage: 250.1+ KB

In [14]:
# Ta ej bort denna cell

### 5 Printa rad 5 till rad 10 (inkluderat 10) med hjälp av .iloc

In [15]:
df.iloc[5:11]

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_result,usd_funding_goal,company_address
5,2021765829ID,Feels Like Home is Going On Tour,Rock,Music,USD,2013-05-01,5000.0,2013-04-10 01:42:03,5490.69,successful,93,US,74996$ usd,5490.69,5000.00,"Gonzalez Landing, 20367"
6,923683665ID,Sarah’s Journey: Empowering the Dreams of Disp...,Children's Books,Publishing,SEK,2016-12-19,218000.0,2016-11-15 19:13:46,227101.00,successful,352,SE,67246$ usd,24593.47,23607.89,"Hall Loaf, 09759"
7,397532230ID,James Clark's Lonely Hearts Rugby Clwb Film & ...,Music,Music,GBP,2014-02-04,300.0,2014-01-07 23:34:41,624.00,successful,26,GB,61172$ usd,1018.79,489.80,"Cunningham Throughway, 66540"
8,181163322ID,Chosen Kin: A New Superhero Series & Interacti...,Webseries,Film & Video,USD,2017-02-02,5000.0,2017-01-03 06:54:08,156.00,failed,5,US,96858$ usd,156.00,5000.00,"Bullock Skyway, 28207"
9,1616507003ID,Adventures in Oz: Beyond the Deadly Desert,Games,Games,USD,2011-12-02,3000.0,2011-11-01 00:00:10,520.00,failed,17,US,82928$ usd,520.00,3000.00,"Harris Estates, 48703"
10,373344194ID,Moonlight Vulture,Restaurants,Food,USD,2016-01-04,10000.0,2015-12-14 15:23:00,10727.00,successful,102,US,51152$ usd,10727.00,10000.00,"Bryant Manor, 16806"

In [16]:
# Ta ej bort denna cell

### 6 Byt index (radernas namn) så att index är baserat på den befintliga kolumnen ID, ändringen ska vara permanent (använd inte inplace)

In [17]:
df = df.set_index("ID")

In [18]:
# Ta ej bort denna cell

### 7 Displaya raderna med indexet "121816660ID" till "1503277376ID" med hjälp av .loc
- Förklara varför en dataframe på många sätt är en blandning mellan en lista och dictionary, använd .iloc och .loc när du argumenterar

In [19]:
# .iloc is used for displaying integers e.g: .iloc[0, 1] while .loc is used for displaying index or column names, e.g: .loc["row_label", "column_name"]

# This means .iloc can be seen as a "list" because we would use a list to display a certain amount of numbers. Also .iloc cannot be used to fetch a certain data (we cant find specific data if we wanted to search by the "key" value - we need the index value)
# my_list = [1, 2, 3]
# print(my_list)

# on the other hand .loc can be seen as a "dictionary", we can find certain data by serching for the "label" - e.g: if I want to find a specific data I can use:
#  .loc["category", "games"]
# shows: all the data that has "games" in the row.

df.loc["121816660ID" : "1503277376ID"]

,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_result,usd_funding_goal,company_address
ID,,,,,,,,,,,,,,,
121816660ID,Dusk - Open World Survival Horror (Canceled),Video Games,Games,GBP,2015-12-19,50000.0,2015-11-18 01:53:10,1625.0,canceled,58,GB,53482$ usd,2422.88,74550.09,"Payne Isle, 42813"
49882738ID,Eatsleeptrainrepeat,Web,Technology,SEK,2014-12-24,180000.0,2014-11-24 21:47:27,0.0,failed,0,SE,64632$ usd,0.00,23054.76,"Laura Stream, 08932"
1503277376ID,FLARE Video Project,Shorts,Film & Video,USD,2011-03-12,5000.0,2011-02-10 20:32:26,5025.0,successful,9,US,99272$ usd,5025.00,5000.00,"Andrew Pike, 24782"

In [20]:
# Ta ej bort denna cell

### 8 Displaya alla rader med currencyn "USD" genom att använda en mask

In [21]:
mask = df["currency"] == "USD"

df[mask]

,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_result,usd_funding_goal,company_address
ID,,,,,,,,,,,,,,,
1054480724ID,Luminoodle COLOR & BASECAMP: Versatile & Porta...,Product Design,Design,USD,2016-04-22,25000.0,2016-03-22 16:39:57,408052.00,successful,5085,US,98849$ usd,408052.00,25000.0,"Mary Grove, 30815"
1317034686ID,Liberty's work was accepted into the Library o...,Shorts,Film & Video,USD,2017-02-23,1100.0,2017-02-03 07:26:57,1106.00,successful,10,US,52486$ usd,1106.00,1100.0,"Garcia Tunnel, 77525"
1503277376ID,FLARE Video Project,Shorts,Film & Video,USD,2011-03-12,5000.0,2011-02-10 20:32:26,5025.00,successful,9,US,99272$ usd,5025.00,5000.0,"Andrew Pike, 24782"
2021765829ID,Feels Like Home is Going On Tour,Rock,Music,USD,2013-05-01,5000.0,2013-04-10 01:42:03,5490.69,successful,93,US,74996$ usd,5490.69,5000.0,"Gonzalez Landing, 20367"
181163322ID,Chosen Kin: A New Superhero Series & Interacti...,Webseries,Film & Video,USD,2017-02-02,5000.0,2017-01-03 06:54:08,156.00,failed,5,US,96858$ usd,156.00,5000.0,"Bullock Skyway, 28207"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
867650362ID,SideWayz Theatre's First Production Fund,Theater,Theater,USD,2016-03-23,2500.0,2016-03-03 23:30:22,25.00,failed,1,US,70106$ usd,25.00,2500.0,"Fernandez Cliff, 07444"
1512412268ID,THE LOVE & MISERY OF A MOONSHINE MIND Project,Publishing,Publishing,USD,2012-10-11,4850.0,2012-09-14 23:43:32,40.00,failed,2,US,77334$ usd,40.00,4850.0,"Williams Junction, 45598"
508267839ID,Mall-World Animated Series - Comedy,Animation,Film & Video,USD,2016-12-19,25000.0,2016-11-04 00:45:31,86.00,failed,2,US,95565$ usd,86.00,25000.0,"Elaine Point, 97758"
945357371ID,Behind the Food Carts Road Trip,Photography,Photography,USD,2014-02-04,5000.0,2014-01-14 23:48:24,5610.00,successful,77,US,86498$ usd,5610.00,5000.0,"Nancy Dam, 25971"
1093469237ID,Paintball Robot,Technology,Technology,USD,2011-03-23,15000.0,2011-02-11 23:55:07,1233.00,failed,18,US,72847$ usd,1233.00,15000.0,"Kennedy Motorway, 67176"

In [22]:
# Ta ej bort denna cell

### 9 kolumnen "pledged" har en hel del värden med 0.0. Ändra dessa till NaN-datatypen istället, använd exempelvis .loc

In [23]:
df["pledged"] = df["pledged"].replace(0, np.nan)

print(df.isna().sum())

name                    0
category                0
main_category           0
currency                0
deadline                0
goal                    0
launched                0
pledged               280
state                   0
backers                 0
country                 0
usd pledged             0
usd_pledged_result      0
usd_funding_goal        0
company_address         0
dtype: int64

### 10 Printa ut alla rader som har NaN med sina vanliga värden (dvs. det ska inte bara vara True / False), ___Du ska använda dig av en metod/funktion___

In [24]:
# Du ska **INTE** göra så här: ks[ks["pledged"] == np.NaN] - du kan ju testa, det kommer inte att fungera!
df[df.isna().any(axis=1)]

,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_result,usd_funding_goal,company_address
ID,,,,,,,,,,,,,,,
49882738ID,Eatsleeptrainrepeat,Web,Technology,SEK,2014-12-24,180000.0,2014-11-24 21:47:27,NaN,failed,0,SE,64632$ usd,0.0,23054.76,"Laura Stream, 08932"
1384707351ID,Batman Band Builder for Ios and Android (Cance...,Games,Games,GBP,2015-10-28,500.0,2015-09-28 21:17:03,NaN,canceled,0,GB,50983$ usd,0.0,766.99,"Barbara Islands, 71175"
1511392096ID,Criss Cross Quail acres,Farms,Food,USD,2015-02-20,30000.0,2015-01-21 21:23:08,NaN,failed,0,US,80915$ usd,0.0,30000.00,"Stacey Loaf, 25341"
1616831393ID,Help us construct with music (Canceled),Music,Music,USD,2011-04-09,10000.0,2011-03-10 05:20:04,NaN,canceled,0,US,86018$ usd,0.0,10000.00,"Jill Course, 75981"
1992107184ID,Community Art Wall (Canceled),Public Art,Art,USD,2013-07-28,6750.0,2013-05-29 22:00:17,NaN,canceled,0,US,85307$ usd,0.0,6750.00,"Collins Pike, 12819"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
625585267ID,Rosie the hippo: Do I have to share my toys? (...,Children's Books,Publishing,USD,2015-12-16,3000.0,2015-11-16 18:31:08,NaN,canceled,0,US,61783$ usd,0.0,3000.00,"Jennifer Trail, 37296"
615895406ID,Kombat Komedian 2,Experimental,Film & Video,EUR,2015-08-15,2000.0,2015-06-18 01:01:07,NaN,failed,0,IT,63965$ usd,0.0,2256.19,"Harmon Walk, 31405"
603589651ID,The beginning,Animation,Film & Video,DKK,2017-09-26,35000.0,2017-08-27 23:22:06,NaN,failed,0,DK,77101$ usd,0.0,5552.21,"Shaw Shore, 91720"
374290795ID,Soul Sessions with Yolanda Stephens (Canceled),Music,Music,USD,2015-09-30,50000.0,2015-08-18 21:59:21,NaN,canceled,0,US,71133$ usd,0.0,50000.00,"Fitzpatrick Alley, 18274"
932817729ID,Chipps and Dipps,Tabletop Games,Games,USD,2016-11-16,35000.0,2016-10-18 21:59:14,NaN,canceled,0,US,53455$ usd,0.0,35000.00,"Stanley Falls, 53083"

In [25]:
# Ta ej bort denna cell

### 11 Skapa en ny kolumn som är heter pledged_real_diff som representerar skillnaden i USD mellan pledged usd och usd_pledged_result.
Hint: Du kommer behöva "cleana" "pledged usd" så att du kan utföra matematiska operationer på det genom att först städa bort onödig text och sedan konvertera det till en float.

In [26]:
#df["pledged_real_diff"]
#df.info()
#df
#df["usd_pledged_result"] - df["usd pledged"]
#df["usd pledged"].sample(50)
#df["usd_pledged_result"].sample(50)

# Step one - check column information - does the columns have same datatype? NO
# usd pledged got 2345098$  got("$" "usd" "space") and is a (object)
# usd_pledged_result got  29348.00 (float64)

# Clean data - convert object to float (easier to do math operations)
# remove $ and usd with .replace and regex pattern [\$,usd ] <- removes dollar sign, "usd" and any spaces. and replace with "". then convert to float with .astype(float)


#Prefix your string with an r to tell Python not to treat backslashes specially:
df["usd pledged"] = df["usd pledged"].replace(r'[\$,usd ]', '', regex=True).astype(float)

# Sanity check - works!
df["usd pledged"].sample(10)
df["usd_pledged_result"].sample(10)

# Step two - do maths..
# Take small - big number. Else the maths gets incorrect.

df["pledged_real_diff"] = df["usd_pledged_result"] - df["usd pledged"]
df

ID
857147327ID     89545.0
1684254929ID    96586.0
170238461ID     98484.0
204170581ID     61494.0
1809184487ID    90667.0
1206170087ID    69753.0
206230258ID     98895.0
102192889ID     99542.0
193758386ID     62800.0
1662931029ID    67284.0
Name: usd pledged, dtype: float64

ID
1512618683ID        25.00
187184513ID        160.00
956683985ID       2325.00
1948295247ID        30.00
1562480378ID    108077.00
1709478676ID         1.60
1478977881ID       139.00
1667809064ID      2270.00
1789531329ID       248.47
1679502237ID         0.00
Name: usd_pledged_result, dtype: float64

,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_result,usd_funding_goal,company_address,pledged_real_diff
ID,,,,,,,,,,,,,,,,
1054480724ID,Luminoodle COLOR & BASECAMP: Versatile & Porta...,Product Design,Design,USD,2016-04-22,25000.0,2016-03-22 16:39:57,408052.0,successful,5085,US,98849.0,408052.00,25000.00,"Mary Grove, 30815",309203.00
1317034686ID,Liberty's work was accepted into the Library o...,Shorts,Film & Video,USD,2017-02-23,1100.0,2017-02-03 07:26:57,1106.0,successful,10,US,52486.0,1106.00,1100.00,"Garcia Tunnel, 77525",-51380.00
121816660ID,Dusk - Open World Survival Horror (Canceled),Video Games,Games,GBP,2015-12-19,50000.0,2015-11-18 01:53:10,1625.0,canceled,58,GB,53482.0,2422.88,74550.09,"Payne Isle, 42813",-51059.12
49882738ID,Eatsleeptrainrepeat,Web,Technology,SEK,2014-12-24,180000.0,2014-11-24 21:47:27,NaN,failed,0,SE,64632.0,0.00,23054.76,"Laura Stream, 08932",-64632.00
1503277376ID,FLARE Video Project,Shorts,Film & Video,USD,2011-03-12,5000.0,2011-02-10 20:32:26,5025.0,successful,9,US,99272.0,5025.00,5000.00,"Andrew Pike, 24782",-94247.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
867650362ID,SideWayz Theatre's First Production Fund,Theater,Theater,USD,2016-03-23,2500.0,2016-03-03 23:30:22,25.0,failed,1,US,70106.0,25.00,2500.00,"Fernandez Cliff, 07444",-70081.00
1512412268ID,THE LOVE & MISERY OF A MOONSHINE MIND Project,Publishing,Publishing,USD,2012-10-11,4850.0,2012-09-14 23:43:32,40.0,failed,2,US,77334.0,40.00,4850.00,"Williams Junction, 45598",-77294.00
508267839ID,Mall-World Animated Series - Comedy,Animation,Film & Video,USD,2016-12-19,25000.0,2016-11-04 00:45:31,86.0,failed,2,US,95565.0,86.00,25000.00,"Elaine Point, 97758",-95479.00
945357371ID,Behind the Food Carts Road Trip,Photography,Photography,USD,2014-02-04,5000.0,2014-01-14 23:48:24,5610.0,successful,77,US,86498.0,5610.00,5000.00,"Nancy Dam, 25971",-80888.00
1093469237ID,Paintball Robot,Technology,Technology,USD,2011-03-23,15000.0,2011-02-11 23:55:07,1233.0,failed,18,US,72847.0,1233.00,15000.00,"Kennedy Motorway, 67176",-71614.00

### 12 Displaya hur många kickstarterprojekt det finns uppdelat på kategori med hjälp av kolumnen main_category

In [27]:
df["main_category"].unique()

array(['Design', 'Film & Video', 'Games', 'Technology', 'Music',
       'Publishing', 'Food', 'Crafts', 'Art', 'Journalism', 'Fashion',
       'Comics', 'Dance', 'Theater', 'Photography'], dtype=object)

In [28]:
df["main_category"].value_counts()

main_category
Film & Video    375
Music           272
Publishing      198
Games           186
Art             154
Design          153
Technology      150
Food            142
Fashion         102
Photography      62
Theater          57
Crafts           56
Comics           47
Journalism       23
Dance            23
Name: count, dtype: int64

In [29]:
# Ta ej bort denna cell

### 13 Vad är det högsta resultatet för usd_pledged_result? Du ska använda dig av en metod.

In [30]:
df["usd_pledged_result"].max()

np.float64(1021481.0)

In [31]:
# Ta ej bort denna cell

### 14 Visa de projekten med minst "usd_pledged_result" - använd dig av .min()
Du ska inte enbart visa värdet, utan hela raderna

Tips: Använd en mask!

In [32]:
mask = df["usd_pledged_result"] == df["usd_pledged_result"].min()

df[mask]

,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_result,usd_funding_goal,company_address,pledged_real_diff
ID,,,,,,,,,,,,,,,,
49882738ID,Eatsleeptrainrepeat,Web,Technology,SEK,2014-12-24,180000.0,2014-11-24 21:47:27,NaN,failed,0,SE,64632.0,0.0,23054.76,"Laura Stream, 08932",-64632.0
1384707351ID,Batman Band Builder for Ios and Android (Cance...,Games,Games,GBP,2015-10-28,500.0,2015-09-28 21:17:03,NaN,canceled,0,GB,50983.0,0.0,766.99,"Barbara Islands, 71175",-50983.0
1511392096ID,Criss Cross Quail acres,Farms,Food,USD,2015-02-20,30000.0,2015-01-21 21:23:08,NaN,failed,0,US,80915.0,0.0,30000.00,"Stacey Loaf, 25341",-80915.0
1616831393ID,Help us construct with music (Canceled),Music,Music,USD,2011-04-09,10000.0,2011-03-10 05:20:04,NaN,canceled,0,US,86018.0,0.0,10000.00,"Jill Course, 75981",-86018.0
1992107184ID,Community Art Wall (Canceled),Public Art,Art,USD,2013-07-28,6750.0,2013-05-29 22:00:17,NaN,canceled,0,US,85307.0,0.0,6750.00,"Collins Pike, 12819",-85307.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
625585267ID,Rosie the hippo: Do I have to share my toys? (...,Children's Books,Publishing,USD,2015-12-16,3000.0,2015-11-16 18:31:08,NaN,canceled,0,US,61783.0,0.0,3000.00,"Jennifer Trail, 37296",-61783.0
615895406ID,Kombat Komedian 2,Experimental,Film & Video,EUR,2015-08-15,2000.0,2015-06-18 01:01:07,NaN,failed,0,IT,63965.0,0.0,2256.19,"Harmon Walk, 31405",-63965.0
603589651ID,The beginning,Animation,Film & Video,DKK,2017-09-26,35000.0,2017-08-27 23:22:06,NaN,failed,0,DK,77101.0,0.0,5552.21,"Shaw Shore, 91720",-77101.0
374290795ID,Soul Sessions with Yolanda Stephens (Canceled),Music,Music,USD,2015-09-30,50000.0,2015-08-18 21:59:21,NaN,canceled,0,US,71133.0,0.0,50000.00,"Fitzpatrick Alley, 18274",-71133.0
932817729ID,Chipps and Dipps,Tabletop Games,Games,USD,2016-11-16,35000.0,2016-10-18 21:59:14,NaN,canceled,0,US,53455.0,0.0,35000.00,"Stanley Falls, 53083",-53455.0

In [33]:
# Ta ej bort denna cell

### 15 Hitta alla rader som innehåller ordet "Cross" i kolumnen "name" med hjälp av string-metoder och displaya högsta värdet för kolumnen "pledged"

In [34]:
df[df["name"].str.contains("Cross", case=True)]["pledged"].max()

np.float64(8618.5)

In [35]:
# Ta ej bort denna cell

## Sektion 2

### 16 Displaya hur många kickstarterprojekt uppdelat på kategori med hjälp av kolumnen main_category. Displaya topp 5 sorterat från högst till lägst.

In [36]:
df["main_category"].value_counts().head(5)

main_category
Film & Video    375
Music           272
Publishing      198
Games           186
Art             154
Name: count, dtype: int64

In [37]:
# Ta ej bort denna cell

### 17 Displaya de top 10 ovanligaste KOMBINATIONERNA av "main_category" och "category" som är country "US"

In [ ]:
# df["main_category"]
# df["category"]

# Filter on country. This shows all the rows with us in the column country.
#df[df["country"] == "US"]

# Group main category and category. This shows both main category and category columns
df.groupby(["main_category", "category"]).size().sort_values().head()



# Counting:
# df["main_category"].value_counts().tail()
# df["category"].value_counts().tail()

main_category  category
Art            Installations    1
Comics         Events           1
Art            Textiles         1
               Video Art        1
Comics         Anthologies      1
dtype: int64

In [39]:
# Ta ej bort denna cell

### 18 Dela upp projekten i grupper baserat på main_category, vad är den genomsnittliga funding-målet dom har (usd_funding_goal). Sortera resultatet från högt till lågt

In [83]:
# What to do: 

# Split projects to groups based on main_category
# Get the avrage usd funding goal
# Sort the values from high to low

df.groupby("main_category")["usd_funding_goal"].mean().sort_values(ascending=False)

main_category
Art             666092.309286
Technology       50913.101867
Games            33791.858656
Food             31883.745070
Theater          27964.739298
Film & Video     22852.615627
Publishing       20830.815909
Design           19979.825948
Fashion          15168.148725
Music            11747.886985
Photography       9095.636613
Crafts            7852.780536
Journalism        7384.004348
Dance             5884.845217
Comics            4545.462553
Name: usd_funding_goal, dtype: float64

In [47]:
# Ta ej bort denna cell

### 19 Displaya en sammanställning av samma gruppering som förra uppgiften. Den ska nu innehålla flera kolumner med minst genomsnitt, max, min, count
- Använd först .describe och displaya din output
- Använd .agg() och displaya din output, du ska endast inkludera genomsnitt, max, min, count

In [65]:
#df.groupby("main_category")["usd_funding_goal"].mean().sort_values(ascending=False)


df.groupby("main_category")["usd_funding_goal"].describe()

df.groupby("main_category")["usd_funding_goal"].agg(['mean', 'max', 'count', 'min'])

,count,mean,std,min,25%,50%,75%,max
main_category,,,,,,,,
Art,154.0,666092.309286,8.057100e+06,75.00,1500.0000,3491.06,10000.0000,1.000000e+08
Comics,47.0,4545.462553,4.111874e+03,99.00,1500.0000,3500.00,6000.0000,2.224034e+04
Crafts,56.0,7852.780536,1.439111e+04,20.00,706.1600,2750.00,8000.0000,6.962980e+04
Dance,23.0,5884.845217,6.328256e+03,350.00,2100.0000,4000.00,6529.4950,2.495840e+04
Design,153.0,19979.825948,3.112554e+04,1.00,3300.0000,10000.00,22500.0000,2.280606e+05
Fashion,102.0,15168.148725,5.088161e+04,158.18,1500.0000,5000.00,12818.4025,5.000000e+05
Film & Video,375.0,22852.615627,5.832066e+04,15.00,2244.9000,6000.00,20000.0000,7.500000e+05
Food,142.0,31883.745070,6.601281e+04,0.89,3550.0000,10000.00,33200.4075,5.000000e+05
Games,186.0,33791.858656,9.787867e+04,15.00,2716.6325,9000.00,20821.8175,7.923763e+05
Journalism,23.0,7384.004348,7.684875e+03,500.00,1857.0150,4865.00,9250.0000,2.700000e+04
Music,272.0,11747.886985,4.720634e+04,111.60,1787.7050,3929.10,8500.0000,7.256368e+05
Photography,62.0,9095.636613,1.252610e+04,100.00,2000.0000,5000.00,10000.0000,7.500000e+04
Publishing,198.0,20830.815909,1.429845e+05,10.00,2000.0000,5000.00,10000.0000,2.000000e+06
Technology,150.0,50913.101867,1.030981e+05,1.00,6000.0000,20000.00,50000.0000,9.000614e+05
Theater,57.0,27964.739298,1.323266e+05,100.00,1500.0000,3814.76,10000.0000,1.000000e+06

                        mean           max  count     min
main_category
Art            666092.309286  1.000000e+08    154   75.00
Comics           4545.462553  2.224034e+04     47   99.00
Crafts           7852.780536  6.962980e+04     56   20.00
Dance            5884.845217  2.495840e+04     23  350.00
Design          19979.825948  2.280606e+05    153    1.00
Fashion         15168.148725  5.000000e+05    102  158.18
Film & Video    22852.615627  7.500000e+05    375   15.00
Food            31883.745070  5.000000e+05    142    0.89
Games           33791.858656  7.923763e+05    186   15.00
Journalism       7384.004348  2.700000e+04     23  500.00
Music           11747.886985  7.256368e+05    272  111.60
Photography      9095.636613  7.500000e+04     62  100.00
Publishing      20830.815909  2.000000e+06    198   10.00
Technology      50913.101867  9.000614e+05    150    1.00
Theater         27964.739298  1.000000e+06     57  100.00

In [66]:
# Ta ej bort denna cell

### 20 Gruppera baserat på kolumnen "state" och displaya genomsnittet av backers (dvs. antal folk som betalat pengar för att stötta projektet). Vad drar du för slutsats? Det räcker med max 2 meningar.

In [ ]:
#df.groupby("main_category")["usd_funding_goal"].mean().sort_values(ascending=False)


df.groupby("state")["backers"].mean()

# Successful has a larger mean than the failed and canceled states. 
# This shows that people that backed a successful kickstart usually tend to back successful kickstart projects.

state
canceled       22.548544
failed         17.244782
live           29.142857
successful    198.752890
suspended      34.555556
undefined       0.000000
Name: backers, dtype: float64

In [43]:
# Ta ej bort denna cell

### 21 Använd .apply() 
1. Undersök vilka kategorier det finns i kolumnen "state"
2. Skapa en funktion som baserat på värdena i kolumnen state är, modifierar kolumnen "usd_funding_goal" med en * om det står success, "!" för failure eller canceled, "---" för "suspended".
3. Displaya ett sample av 20 rader från din modifierade kolumn

Index(['name', 'category', 'main_category', 'currency', 'deadline', 'goal',
       'launched', 'pledged', 'state', 'backers', 'country', 'usd pledged',
       'usd_pledged_result', 'usd_funding_goal', 'company_address',
       'pledged_real_diff'],
      dtype='object')

array(['successful', 'canceled', 'failed', 'live', 'undefined',
       'suspended'], dtype=object)

ID
657726192ID         failed
701498064ID     successful
1041473111ID        failed
1289078406ID    successful
447025479ID         failed
1436231205ID        failed
959076303ID     successful
1805214384ID        failed
1786210055ID    successful
1895575607ID    successful
Name: state, dtype: object